### ISSUE TITLE
I am getting error 

### ISSUE THREAD

**Issue by nksaroj** [BelkaLab/Android-Toggle-Switch#11]
android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class <unknown>
                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                        at belka.us.androidtoggleswitch.widgets.util.ToggleSwitchButton.<init>(ToggleSwitchButton.java:0)
                                                                                        at belka.us.androidtoggleswitch.widgets.BaseToggleSwitch.addToogleBtn(BaseToggleSwitch.java:179)
                                                                                        at belka.us.androidtoggleswitch.widgets.BaseToggleSwitch.buildToggleButtons(BaseToggleSwitch.java:216)
                                                                                        at belka.us.androidtoggleswitch.widgets.ToggleSwitch.buildToggleButtons(ToggleSwitch.java:51)
                                                                                        at belka.us.androidtoggleswitch.widgets.BaseToggleSwitch.setLabels(BaseToggleSwitch.java:273)
                                                                                        at com.cba.commsec.android.view.fragment.markets.tabs.MarketMovers.onNewViewCreated(MarketMovers.java:69)
                                                                                        at com.cba.commsec.lib.android.bootstrap.view.BaseFragment.onCreateView(BaseFragment.java:265)
                                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                                                        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                                                        at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                                        at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
                                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
                                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
                                                                                        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
                                                                                        at android.view.View.measure(View.java:18794)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                        at android.view.View.measure(View.java:18794)
                                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                                        at android.support.percent.PercentRelativeLayout.onMeasure(PercentRelativeLayout.java:105)
                                                                                        at android.view.View.measure(View.java:18794)
                                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                                        at android.view.View.measure(View.java:18794)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                        at android.view.View.measure(View.java:18794)
                                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                                        at android.view.View.measure(View.java:18794)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                        at android.view.View.measure(View.java:18794)
                                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                                        at android.view.View.measure(View.java:18794)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                        at android.view.View.measure(View.java:18794)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                        at android.view.View.measure(View.java:18794)
                                                                                    	at android

**Comment by llollox** [comment]
Please try another time with the new version of the library 1.2.0.
